image: node:12-buster

stages:
  - build
  - test
  - publish
  - docs

build:
  stage: build
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - dist/

build_docs:
  stage: docs
  script:
    - npm i
    - npm run build
    - npx doca init -i schemas
    - cd documentation && npm i && npm run build:nojs
    - AWS_ACCESS_KEY_ID=${DOCS_S3_ACCESS_KEY} AWS_SECRET_ACCESS_KEY=${DOCS_S3_SECRET_ACCESS_KEY} AWS_DEFAULT_REGION=${DOCS_S3_REGION} aws s3 sync build s3://${DOCS_S3_SCHEMA_BUCKET} --include "*"
    - AWS_ACCESS_KEY_ID=${DOCS_S3_ACCESS_KEY} AWS_SECRET_ACCESS_KEY=${DOCS_S3_SECRET_ACCESS_KEY} AWS_DEFAULT_REGION=${DOCS_S3_REGION} aws cloudfront create-invalidation --distribution-id ${DOCS_CLOUDFRONT_ID} --paths /index.html /
  artifacts:
    paths:
      - ./documentation/build
    expire_in: 4 weeks
    when: always
  only:
    refs:
      - master
  tags:
    - awscli

test:
  stage: test
  script:
    - npm i
    - npm run typecheck
    - npm run lint
    - npm run test:ci
  artifacts:
    reports:
      junit: junit.xml

publish:
  stage: publish
  only:
    refs:
      - master
  script:
    - npx @manuscripts/publish
