stages:
- build
- test
- deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  tags:
    - nodejs

test:
  stage: test
  script:
    - npm install
    - npm t
  tags:
    - nodejs

publish:
  stage: deploy
  only:
    refs:
      - master
  script:
    - echo Running release
    - npx ci-publish || true
  tags:
    - nodejs
