image: node:12-buster

stages:
  - build
  - test
  - publish
  - docs

build:
  stage: build
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - dist/

build_docs:
  stage: docs
  script:
    - npm i
    - npm run build
  only:
    refs:
      - master
  tags:
    - awscli

test:
  stage: test
  script:
    - npm i
    - npm run typecheck
    - npm run lint
    - npm run test:ci
  artifacts:
    reports:
      junit: junit.xml

publish:
  stage: publish
  only:
    refs:
      - master
  script:
    - npx @manuscripts/publish
